version: '2.1'
services:
    postgres:
        image: postgres
        container_name: dev-postgres
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_PASSWORD=1234
        volumes:
            - ${HOME}/postgres-data/:/var/lib/postgresql/data

services: 
    pgAdmin:
        image: dpage/pgadmin4
        container_name: dev-pgadmin
        ports: 
            - "80:80"
        environment: 
            - PGADMIN_DEFAULT_EMAIL=user@domain.local
            - PDADMIN_DEFAULT_PASSWORD=1234
        depends_on: 
            postgres
